apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-gateway
  namespace: egress-ns
  labels:
    egress-code: red
spec:
  replicas: 1
  selector:
    matchLabels:
      egress-code: red
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv4pools: "[\"10.10.13.0/31\"]"
      labels:
        egress-code: red
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: egress-gateway
        image: quay.io/tigera/egress-gateway:v3.0.0
        env:
        - name: EGRESS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 0
