apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: hourly-zone-policy-audit-report
spec:
  reportType: policy-audit
  endpoints:
    namespaces:
      names: ["development", "staging", "production"]
  schedule: 0 * * * *
