kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: database-policy-stage
  namespace: staging
spec:
  podSelector:
    matchLabels:
      app: database
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: backend
      ports:
      - protocol: TCP
        port: 2379
