apiVersion: v1
kind: Namespace
apiVersion: v1
metadata:
  name: staging
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: staging
  labels:
    app: database
spec:
  ports:
  - port: 2379
    name: http
  selector:
    app: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: staging
  labels:
    app: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: staging
spec:
  selector:
     matchLabels:
        app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
        network: dev
        zone: database
        version: v1
    spec:
      securityContext:
            runAsUser: 0
      serviceAccountName: database
      containers:
      - name: database
        image: spikecurtis/yaobank-database:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2379
        command: ["etcd"]
        args:
          - "-advertise-client-urls"
          - "http://database:2379"
          - "-listen-client-urls"
          - "http://0.0.0.0:2379"
      nodeSelector:
        labnode: worker2
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: staging
  labels:
    app: backend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: staging
  labels:
    app: staging
    database: reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: staging
spec:
  selector:
     matchLabels:
        app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        network: dev
        zone: backend
        version: v1
    spec:
      securityContext:
            runAsUser: 0
      serviceAccountName: backend
      containers:
      - name: backend
        image: pranhdstud/backend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: staging
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30182
    name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: staging
  labels:
    app: staging
    summary: reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging
spec:
  selector:
     matchLabels:
        app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        network: dev
        zone: frontend
        version: v1
    spec:
      securityContext:
            runAsUser: 0
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: pranhdstud/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector:
        labnode: worker1
---
